---
title: "NYC Schools Perceptions"
author: "Eda AYDIN"
date: "30 04 2021"
output:
  pdf_document:
    toc: yes
---

# New York City Schools Survey Data

```{r}
# Load the packages 

library(readr)
library(dplyr)
library(stringr)
library(purrr)
library(tidyr)
library(ggplot2)
```

```{r}
# Import the data

combined <- read_csv("combined.csv")
survey <- read_tsv("masterfile11_gened_final.txt")
survey_d75 <- read_tsv("masterfile11_d75_final.txt")
```

# Simplifying the Dataframes

```{r}
# Select columns needed for analysis
survey_select <- survey %>%
  filter(schooltype == "High School") %>%
  select(dbn:saf_p_11)

survey_d75_select <-survey_d75 %>%
  select(dbn:com_s_11)
```
 
# Creating a Single Dataframe for Analysis

```{r}
# Combine 'survey' and 'survey_d75' data frames
survey_total <- survey_select %>%
  bind_rows(survey_d75_select)
```

```{r}
# Rename 'survey_total' variable 'dbn' to 'DBN' so can use as key
# to join with 'combined' data frame

survey_total <- survey_total %>%
  rename (DBN = dbn)
```

```{r}
# Join the 'combined' and 'survey_total' data frames.
combined_survey <- combined %>%
  left_join(survey_total, by="DBN")
```


# Look for Interesting Correlations and Examine Relationships Using Scatter Plots

```{r}
cor_mat <- combined_survey %>% 
  select(avg_sat_score, saf_p_11:com_s_11) %>%
  cor(use = "pairwise.complete.obs")

cor_tib <- cor_mat %>%
  as_tibble(rownames = "variable")
```

```{r}
strong_cors <- cor_tib %>%
  select(variable, avg_sat_score) %>%
  filter(avg_sat_score > 0.25 | avg_sat_score < -0.25)
```

```{r}
create_scatter <- function(x, y) {     
  ggplot(data = combined_survey) + 
    aes_string(x = x, y = y) +
    geom_point(alpha = 0.3) +
    theme(panel.background = element_rect(fill = "white"))
}
```

```{r}
x_var <- strong_cors$variable[2:5]
y_var <- "avg_sat_score"
  
map2(x_var, y_var, create_scatter)
```

```{r}
combined_survey_gather <- combined_survey %>%
  pivot_longer(cols = saf_p_11:com_s_11,
               names_to = "survey_question",
               values_to = "score")
```

```{r}
combined_survey_gather <- combined_survey_gather %>%
  mutate(response_type = str_sub(survey_question, 4, 6)) %>%   
  mutate(question = str_sub(survey_question, 1, 3))
```



# Differences in Student, Parent, and Teacher Perceptions: Reshape the Data

```{r}
combined_survey_gather <- combined_survey_gather %>%
  mutate(response_type = ifelse(response_type  == "_p_", "parent", 
                                ifelse(response_type == "_t_", "teacher",
                                       ifelse(response_type == "_s_", "student", 
                                              ifelse(response_type == "_to", "total", "NA")))))
```

```{r}
combined_survey_gather %>%
  filter(response_type != "total") %>%
  ggplot(aes(x = question, y = score, fill = response_type)) +
  geom_boxplot()
```